runtime: nodejs10
#env: flex
env_variables:
  PRIVATE_KEY: Q9gHUi2SvWwd5xKUn6Ikh4FqMfxnx0md
  MYSQL_USER: iocuscom_flkUser
  MYSQL_PASSWORD: kWRQ86zjgg8PKrYm
  MYSQL_HOST: iocus.com.br
  MYSQL_DB: iocuscom_flaker

#beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  # cloud_sql_instances: backupsystem:southamerica-east1:backup-system