runtime: nodejs
env: flex
env_variables:
  PRIVATE_KEY: Q9gHUi2SvWwd5xKUn6Ikh4FqMfxnx0md
  MYSQL_DSN: backupsystem:southamerica-east1:backup-system
  MYSQL_USER: user_system
  MYSQL_PASSWORD: p42e7WNVdnfVcS5

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: backupsystem:southamerica-east1:backup-system